version: '3.9'
services:
  react:
    # build: .
    image: react/context
    container_name: react-context-container
    ports:
      - 5000:5000
      - 5001:5001
    entrypoint:
      - 'npm'
    command: run dev
    volumes:
      - .:/home/node/web
    tty: true
