version: '3.9'
services:
  react:
    # build: .
    image: react/context
    container_name: react-context-container
    ports:
      - ${SERVER_PORT:-5000}:${SERVER_PORT:-5000}
    environment:
      - NODE_ENV=development
      - PORT=${SERVER_PORT:-5000}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    entrypoint:
      - 'npm'
    command:
      - 'start'
    volumes:
      - .:/home/node/web
